server:
  port: 9000

spring:
  application:
    name: api-gateway
  zipkin:
    base-url: http://localhost:9411
  cloud:
    compatibility-verifier:
      enabled: false

    gateway:
      routes:
        - id: order
          uri: lb://ORDER
          predicates:
            - Path=/orders/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      enabled: false